# Generated by Django 4.2.27 on 2026-03-31 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temperature',
            fields=[
                ('myid', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_id', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('humidity', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
